const DEFAULT_SYSTEM_TENANT = "SYSTEM_TENANT";
const USER_PERMISSION_MODULE = ["CONT", "COMP", "TEAM", "SETTING", "PROPERTY"];
const USER_PERMISSION_FIELD = ["create", "remove", "update", "display", "export", "import"];
const DEFAULT_LIST_LIMIT = 10;

export { DEFAULT_SYSTEM_TENANT, USER_PERMISSION_MODULE, USER_PERMISSION_FIELD, DEFAULT_LIST_LIMIT };
