name: testing_apk_build
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter

    flutter_svg: ^2.0.9
    flutter_riverpod: ^2.5.1
    cupertino_icons: ^1.0.8

    # Let user pick which apps to block (list installed apps)
    installed_apps: ^1.3.2

    # Open OS settings pages (Usage Access, Overlay, Accessibility)
    app_settings: ^5.1.1
    android_intent_plus: ^5.0.2

    # Request standard permissions (not overlay/usage, but still useful)
    permission_handler: ^11.3.1

    # SYSTEM overlay over other apps (true “draw over apps” window)
    flutter_overlay_window: ^0.4.5

    # Foreground service to keep your watcher alive
    flutter_foreground_task: ^6.4.0

    # Foreground app detection (via UsageStats)
    # usage_stats: ^1.2.0

    http: ^1.2.2

    flutter_localizations:
        sdk: flutter

    intl: ^0.20.2

    dio: ^5.7.0

    flutter_secure_storage: ^9.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/icons/

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package
