name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1

  # Optional: nice icons
  cupertino_icons:
    ^1.0.8

    # Let user pick which apps to block (list installed apps)
  installed_apps: ^1.3.2 # or device_apps

  # Open OS settings pages (Usage Access, Overlay, Accessibility)
  app_settings: ^5.1.1
  android_intent_plus: ^5.0.2

  # Request standard permissions (not overlay/usage, but still useful)
  permission_handler: ^11.3.1

  # SYSTEM overlay over other apps (true “draw over apps” window)
  flutter_overlay_window: ^0.4.5 # uses SYSTEM_ALERT_WINDOW

  # Foreground service to keep your watcher alive
  flutter_foreground_task: ^6.4.0

  # Foreground app detection (via UsageStats)
  usage_stats: ^1.2.0
  http: ^1.5.0

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2 # for date/number formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
